apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ping
spec:
  # Run at 1pm every day to notify the team of the number of PRs waiting code review
  schedule: "0 13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ping
            image: gcr.io/priya-wadhwa/ping:latest
            args: ["-space", "AAAAcfMLLAU"]
          restartPolicy: OnFailure
